### ISSUE TITLE
"Luhmann" is written with two "n"

### ISSUE THREAD

**Issue by chrisgrieser** [Dyldog/luhman-obsidian-plugin#1]
The fact that this plugin is called "Luhman" slightly triggers my OCD ;)

https://en.wikipedia.org/wiki/Niklas_Luhmann

**Comment by Dyldog** [comment]
😆 My bad! I'll update ASAP!

**Comment by Dyldog** [comment]
Fixed

**Comment by chrisgrieser** [comment]
Now there is still the spelling mistake in the repo name 😁
