### ISSUE TITLE
[FEATURE] Hotkey for generating a Zettlekasten ID

### ISSUE THREAD

**Issue by JJger148** [Dyldog/luhman-obsidian-plugin#12]
Please add another Hotkey, so I can generate an ID simply with a Hotkey

**Comment by Eforen** [comment]
I like this idea but it will be low on the priority list and will likely be resolved by #22

**Comment by Eforen** [comment]
If you want to submit a pr that includes a command for that then I would love to see it.

**Comment by Eforen** [comment]
This is likely not needed anymore @JJger148 do you still have a usecase for this after #33  is implimented?

I am closing this for now let me know if you have a remaining usecase
