### ISSUE TITLE
Create node commands makes empty links and it doesn't follow me to real Child or Brother/Sister node

### ISSUE THREAD

**Issue by simakovpa** [Dyldog/luhman-obsidian-plugin#17]

**Comment by Eforen** [comment]
@brannonh why was this closed as far as I can see the issue is not resolved? and there is no comment about it being resolved?

**Comment by brannonh** [comment]
> @brannonh why was this closed as far as I can see the issue is not resolved? and there is no comment about it being resolved?

I was just attempting to clean up old items. If this is still an issue, I'm happy to reopen it. I don't fully understand the title, so some elaboration and/or steps to reproduce would be nice.

**Comment by Eforen** [comment]
I agree it's confusing but they are I believe talking about the same thing that PR #9 addresses. I would resolve the conflict but I don't know how to without permissions on eather repo...
