### ISSUE TITLE
[BUG] Automatic link does not contain separator or title

### ISSUE THREAD

**Issue by DesiQuintans** [Dyldog/luhman-obsidian-plugin#21]
Steps to reproduce:

1. Luhmann settings (v1.1.0, installed from Obsidian community plugin browser):
    - ID matching rule: Separator
    - Add titles automatically: TRUE
    - ID separator: `- ` (that's hyphen and space)
2. Be editing a zettel, and use _Luhmann: New Child Zettel_ or _Luhmann: New Sibling Zettel_ to create a new file.
3. Create the file with any title.

You will find that:

1. The new file has the correct ID-separator-title filename, and
2. The new file has the correct title inside it, BUT
3. When you go back to the zettel that you were previously editing, the link that is automatically placed to go to the new zettel only has the ID and not the separator or title, which makes it a link to a non-existent file. For example, it links to `[[1a3c]]` and not `[[1a3c- My title]]`.

**Comment by Eforen** [comment]
@DesiQuintans does this relate to #24 #17 and/or #6 ?

It looks like it does to me so I am going to close this as duplicate for now but if you believe not then please reopen it.
