### ISSUE TITLE
[FEATURE] Create zettel child/sibling without opening new note

### ISSUE THREAD

**Issue by Eforen** [Dyldog/luhman-obsidian-plugin#22]
I am thinking we should also have some commands for taking selected text and making it into a child or sibling zettel this will allow a user to make zettels while making new content without going to the new page. 

Another option is maybe just make it so when doing the new zettel action it will make 2 options one is okay and open zettel and the other is just stay on the page you are on and add in the IDed link.

Does this sound like something yall want?

**Comment by jamesx4** [comment]
I like the idea of being able to select a block of text and having an option to refactor that into a new child or sibling zettel, replacing the selected text with the link.  This would be similar to capabilities in the note refactor plugin (I think), but with the Luhman UID.   Of course, I'd like to see the new zettel use a template if configured as mentioned in another post.  

Not sure if that's the direction you're describing, but that would be very useful for my use cases.

**Comment by Eforen** [comment]
Yes it would use all the other features basically it would do exactly what it is configured to do when making a note normally except just not make the note.

**Comment by brannonh** [comment]
Love this idea. 👍🏻

**Comment by Eforen** [comment]
I plan to impliment it after we get all these bugs fixed

**Comment by Eforen** [comment]
BTW the selection and refactor you mentioned is already implimented it just does not work right... See: Bug #32

**Comment by Eforen** [comment]
Resolved by #33
