### ISSUE TITLE
Fails to install from obsidian marketplace

### ISSUE THREAD

**Issue by morngrar** [Dyldog/luhman-obsidian-plugin#3]
Currently, clicking the "install" button in obsidian results in a failure (Obsidian v0.12.15)

**Comment by quarterdane** [comment]
I'm having this problem too.  Here's the error message I get when I click the install button in marketplace:
[
<img width="511" alt="Screen Shot 2021-09-07 at 6 46 39 AM" src="https://user-images.githubusercontent.com/67063377/132356023-aa6713f6-6b45-4f17-a70d-f8e480ff4b9d.png">
](url)

**Comment by quarterdane** [comment]
Found the problem.  The release package just has the wrong file in it.  It has package instead of main.

**Comment by morngrar** [comment]
> Found the problem. The release package just has the wrong file in it. It has package instead of main.

Maybe put up a PR so the author can simply merge? I **really** want this, but I'm not well versed in the tech behind these plugins, and I don't have the time to figure it out now.

**Comment by Dyldog** [comment]
I'm really sorry about this! Thank you @morngrar @quarterdane for doing the work I should've done myself.

The issue is fixed and I've been able to download the plugin from the Obsidian store. Again, thank you :)
