### ISSUE TITLE
Next Release - Changelog

### ISSUE THREAD

**Issue by MrMysterius** [Dyldog/luhman-obsidian-plugin#48]
Small change of plans looks like I can't work on this until Saturday I am gona try to get a build out the door around then though.

If you want to help out, one thing that would be really helpful is to collect all the PR numbers into a next build ticket so I don't have to when I ready.

_Originally posted by @Eforen in https://github.com/Dyldog/luhman-obsidian-plugin/issues/43#issuecomment-1498525129_

**Comment by MrMysterius** [comment]
### Added

- #43 Template Usage for new Notes + Settings - Thanks to @MrMysterius 
- #45 Automatic Title Aliases + Settings - Thanks to @electblake 

### Fixed

- #42 Fixed bug where especially for strict mode it wouldn't recognize files as luhman style notes. - *Because of broken regex* - Thanks to @MrMysterius 
- #47 Fixed commands not having any icons on mobile. - Thanks to @electblake

**Comment by MrMysterius** [comment]
Hope This helps @Eforen

**Comment by MrMysterius** [comment]
Quick Reminder @Eforen

**Comment by Eforen** [comment]
v1.2.0 Pushed out with some light pain... Sorry it took so long our release process is not totally smoothed out.
